name: Daily Data Fetch and Update

on:
  schedule:
    # Runs at 18:00 UTC every day
    - cron: '0 19 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data fetch and update script
        run: |
          python scripts/fetch_and_update_data.py

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes if any
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/robertgwx/upgraded-spoon.git
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Automated climate data update"
            git push origin HEAD:main
          else
            echo "No changes to commit or push."
          fi
